/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AdminData;
import Data.Conexion;
import Modelo.Admin;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static java.util.Calendar.HOUR_OF_DAY;
import static java.util.Calendar.MINUTE;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Flor
 */
public class Inicio extends javax.swing.JFrame {
       private String login_usuario;
      private String login_pass;
      private Conexion con;
      Admin a = new Admin();
     private int id_admin = 0;
     private boolean existe= false;
  
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
this.setLocationRelativeTo(null);
    this.setResizable(false);
 this.setTitle("Inicio de Sesión");
 hoy();
 mañana();

       
    }
        public Date hoy() {

         Calendar calendar = new GregorianCalendar(); 
     Date fecha = calendar.getTime();
   SimpleDateFormat formateador = new SimpleDateFormat("' Hoy es 'EEEEEE dd ' de ' MMMM ' - ' HH:mm 'hs'", new Locale("es")); 
 String calendario = formateador.format(fecha);

 System.out.println(calendario);
 return fecha;}
        public Date mañana() {
Calendar cal = new GregorianCalendar();
     cal.add(Calendar.DAY_OF_YEAR, +1); cal.add(HOUR_OF_DAY, - cal.get(HOUR_OF_DAY)); cal.add(Calendar.MINUTE, - cal.get(MINUTE)); //minutosASumar es int.
     Date fechamañana = cal.getTime();
    SimpleDateFormat forma = new SimpleDateFormat("' Mañana es 'EEEEEE dd ' de ' MMMM ' - ' HH:mm 'hs'", new Locale("es")); 
    String mañana = forma.format(fechamañana);
 System.out.println(mañana); return fechamañana;}
    public boolean verificarAdmin() {
        login_usuario = usuario.getText();
        login_pass = pass.getText();

        try {
            con = new Conexion("jdbc:mysql://localhost/sonno", "root", "");
            AdminData hd = new AdminData(con);

            a = hd.buscarAdmin(login_usuario, login_pass);
            if (a.getId_admin() == 0) { //Significa que no encontro ningun administrador
                existe = false;
            } else {
                existe = true;
            }

        } catch (Exception e) {
        }
        return existe;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/sonno.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);

        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña:");

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario)
                    .addComponent(pass)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
         if (usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su ID");
        } else if (pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su Apellido");
 
        }else {
            if (verificarAdmin()) {
                //Si el administrador existe, entonces abro la ventana principal donde el administrador podra:
                // *Ver Agenda
                // Abrir gestor de bandas
                // *Utilizar el ABM de Tipos de Habitaciones
                // *Buscar banda
                this.dispose();
Menu menu  = new Menu(a);
        menu.setVisible(true);
        this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Los datos ingresados no corresponden a un administrador");
                usuario.setText("");
                pass.setText("");
            }
        }

    }//GEN-LAST:event_ingresarActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
              if (usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su usuario");
        } else if (pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
 
        }else {
            if (verificarAdmin()) {
                //Si el administrador existe, entonces abro la ventana principal donde el administrador podra:
                // *Ver Agenda
                // Abrir gestor de bandas
                // *Utilizar el ABM de Tipos de Habitaciones
                // *Buscar banda
                this.dispose();
Menu menu  = new Menu(a);
        menu.setVisible(true);
        this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Los datos ingresados no corresponden a un administrador");
                usuario.setText("");
                pass.setText("");}}
        }
    }//GEN-LAST:event_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
